const jq = require("jquery");

function createServerList() {
  const jsonServers = require("../assets/servers.json");
  if (jsonServers && jsonServers.length > 0) {
    jq("#serverList").append("<!-- AUTO GENERATED BY THE CONTROLLER -->");
    for(server of jsonServers) {
      let tableRow = jq("<tr/>");

      let name = jq("<td/>").append(server.name);
      let ip = jq("<td/>").append(server.ip);
      let port = jq("<td/>").append(server.port);

      let actions = jq("<td/>");
        let connect = jq("<button/>").append("Connect");
        let favorite = jq("<button/>").append("Add to favorite");

      actions.attr("id", "action");
      actions.append([connect, favorite]);

      tableRow.append([name, ip, port, actions]);
      jq("#serverList").append(tableRow);
    }
  }
}

function createFavoriteServerList() {
}

createServerList();
