const jq = require("jquery"),
  fs = require("fs");

(function() {
  angular
    .module("screepsClient", [])
    .controller("serverList", ["$scope", serverList]);
}());

function serverList($scope) {
  // Load server list
  // If file doesn't exist, notify the user to add servers to the list

  $scope.checkServerFile = (cb) => {
    fs.exists("../servers.json", exists => {
      if(exists) {
        cb();
      } else {
        // NOTIFY USER TO ADD SERVERS
        console.log("err");
      }
    });
  }

}

/*const jq = require("jquery"),
  main = require("electron").remote.require("./main");

function createServerList() {
  const jsonServers = require("../assets/servers.json");
  if (jsonServers && jsonServers.length > 0) {
    jq("#serverList").append("<!-- AUTO GENERATED BY THE CONTROLLER -->");
    let cpt = 0;
    for(server of jsonServers) {
      let tableRow = jq("<tr/>");
      let name = jq("<td/>").append(server.name);
      let ip = jq("<td/>").append(server.ip);
      let port = jq("<td/>").append(server.port);

      tableRow.attr("id", cpt);
      tableRow.append([name, ip, port]);
      tableRow.click(e => {
        let serverID = parseInt(e.currentTarget.id);
        console.log(main.selectedServer(serverID));
      });

      jq("#serverList").append(tableRow);
      cpt++;
    }
  }
}

jq(document).ready(() => {
  createServerList();
});
*/
